apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-container
        image: my-go-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
