apiVersion: v1
kind: Pod
metadata:
  name: go-simple-pod
spec:
  containers:
  - name: go-container
    image: golang:1.20-alpine
    command: ["go", "run", "hello.go"]
    volumeMounts:
    - name: code
      mountPath: /go/src/app
  volumes:
  - name: code
    hostPath:
      path: /path/to/your/go/code
